### ISSUE TITLE
Data label value is not there on stacked bar graph

### ISSUE THREAD

**Issue by GouravJ123** [OGcanviz/ChartComponents#2]
Hi, 
is it possible to get the data label value on stacked bar? Please check the attachment for your reference.
![image](https://user-images.githubusercontent.com/78015579/105818926-c42efe00-5fb7-11eb-9db5-dcfc9fd106cd.png)

**Comment by TBag** [comment]
Hi, thanks for your great suggestion.  We've added it to our current sprint and this enhancement will be included with a bunch of other great new features we think you will enjoy in the next release.

**Comment by GouravJ123** [comment]
Hi ,

Thanks for your response.

When can i expect the change? Can you please notify me if its possible.

Regards 
Gourav

**Comment by TBag** [comment]
It will probably be a couple of weeks until we finish all the things we are working on in this sprint, test, and update all the documentation accordingly.

**Comment by GouravJ123** [comment]
By the way, great work.

Please notify me if its possible.


Regards 
Gourav

**Comment by TBag** [comment]
Thanks.  It's possible.  @hubertsui added it to the component last night.  You can expect to see it in our next release in a couple of weeks.

**Comment by GouravJ123** [comment]
Hi Team,

Good Day!

Do you have any update on the release?

Regards
Gourav

**Comment by TBag** [comment]
Hello,

We are still working on all the new enhancements and documentations updates.  It's quite a lot of work so it may take a few more weeks.

**Comment by GouravJ123** [comment]
Hello Team,

Good Day!

Earlier I was able to bind the dynamic data in a stacked bar graph. Now its
throwing error. i have been trying it for the last two days. have you
changed anything. If no, can you please share some documentation.

Regards
Gourav

**Comment by OGcanviz** [comment]
Hi,

We haven't changed anything.  Here's a link to the docs.  https://ogcanviz.github.io/ChartComponents/#/

**Comment by GouravJ123** [comment]
Hi Team, 

Good morning 

Sorry to bother you again. Do you have any update on this?

Regards 
Gourav

**Comment by OGcanviz** [comment]
Hello,

We do not have any updates to share right now.  We still need to finish coding all the new enhancements and making the documentation updates.  It's quite a lot of work.  Thanks for your patience.
